version: "3"

services:
  db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=storytelling
    volumes:
      - pgdata:/bitnami/postgresql
    networks:
      - app-network

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=redis
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami/redis/data
    networks:
      - app-network

volumes:
  pgdata:
  redis_data:

networks:
  app-network:
    driver: bridge
